apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      namespace: default
      labels:
        app: flask-app
    spec:
      containers:
      - image: andersondanw/pyred-hello:v0.4
        imagePullPolicy: IfNotPresent
        name: flask
      restartPolicy: Always
