apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "600"
    imagePullPolicy: IfNotPresent
    name: busybox-2
  restartPolicy: Always
