apiVersion: v1
kind: Pod
metadata:
  name: pyred-pod
  namespace: default
  labels:
    app: pyred-app
spec:
  containers:
  - image: andersondanw/pyred-hello:v0
    imagePullPolicy: IfNotPresent
    name: pyred-container
    ports:
    - containerPort: 6379
  - image: redis
    imagePullPolicy: IfNotPresent
    name: redis
    ports:
    - containerPort: 6379
  restartPolicy: Always
