apiVersion: v1
kind: Pod
metadata:
  name: pyred-pod
  namespace: default
spec:
  containers:
  - image: andersondanw/pyred-hello:v0
    imagePullPolicy: IfNotPresent
    name: pyred-container
  restartPolicy: Always
