apiVersion: v1
kind: Pod
metadata:
  name: pyred-pod
  namespace: default
  labels:
    app: pyred-app
spec:
  containers:
  - image: andersondanw/pyred-hello:v0.3
    imagePullPolicy: IfNotPresent
    name: flask
  - image: redis
    imagePullPolicy: IfNotPresent
    name: redis
  restartPolicy: Always
